In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

# import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/amaanpoonawala/youtube-comments-sentiment-dataset/youtube_comments_cleaned.csv

In [2]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

df=pd.read_csv('youtube_comments_cleaned3.csv')
df.head()

,CommentID,VideoID,VideoTitle,AuthorName,AuthorChannelID,CommentText,Sentiment,Likes,Replies,PublishedAt,CountryCode,CategoryID
0,UgyRjrEdJIPrf68uND14AaABAg,mcY4M9gjtsI,They killed my friend.#tales #movie #shorts,@OneWhoWandered,UC_-UEXaBL1dqqUPGkDll49A,Anyone know what movie this is?,Neutral,0,2,2025-01-15 00:54:55,NZ,1
1,UgxXxEIySAwnMNw8D7N4AaABAg,2vuXcw9SZbA,Man Utd conceding first penalty at home in yea...,@chiefvon3068,UCZ1LcZESjYqzaQRhjdZJFwg,The fact they're holding each other back while...,Positive,0,0,2025-01-13 23:51:46,AU,17
2,UgxB0jh2Ur41mcXr5IB4AaABAg,papg2tsoFzg,Welcome to Javascript Course,@Abdulla-ip8qr,UCWBK35w5Swy1iF5xIbEyw3A,waiting next video will be?,Neutral,1,0,2020-07-06 13:18:16,IN,27
3,UgwMOh95MfK0GuXLLrF4AaABAg,31KTdfRH6nY,Building web applications in Java with Spring ...,@finnianthehuman,UCwQ2Z03nOcMxWozBb_Cv66w,Thanks for the great video.\n\nI don't underst...,Neutral,0,1,2024-09-18 12:04:12,US,27
4,UgxJuUe5ysG8OSbABAl4AaABAg,-hV6aeyPHPA,After a new engine her car dies on her way hom...,@ryoutubeplaylistb6137,UCTTcJ0tsAKQokmHB2qVb1qQ,Good person helping good people.\nThis is how ...,Positive,3,1,2025-01-10 19:39:03,US,2

In [3]:
df.shape

(989258, 12)

In [4]:
df.sample()

,CommentID,VideoID,VideoTitle,AuthorName,AuthorChannelID,CommentText,Sentiment,Likes,Replies,PublishedAt,CountryCode,CategoryID
239499,Ugx2KRJrkpfkmgp1gdd4AaABAg,ZZsrtfBrQfw,Using whetstones to sharpen the kitchen knives!,@MrCinna,UC981uuY0uJyMPbEmPYGFcpg,I need one of those holders,Neutral,0,0,2025-01-12 02:40:45,AU,26

In [5]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989258 entries, 0 to 989257
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   CommentID        989258 non-null  object
 1   VideoID          989258 non-null  object
 2   VideoTitle       989258 non-null  object
 3   AuthorName       989258 non-null  object
 4   AuthorChannelID  989258 non-null  object
 5   CommentText      989258 non-null  object
 6   Sentiment        989258 non-null  object
 7   Likes            989258 non-null  int64
 8   Replies          989258 non-null  int64
 9   PublishedAt      989258 non-null  object
 10  CountryCode      989258 non-null  object
 11  CategoryID       989258 non-null  int64
dtypes: int64(3), object(9)
memory usage: 784.0 MB

In [6]:
print("Data types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nUnique values per column:")
print(df.nunique())

Data types:
CommentID          object
VideoID            object
VideoTitle         object
AuthorName         object
AuthorChannelID    object
CommentText        object
Sentiment          object
Likes               int64
Replies             int64
PublishedAt        object
CountryCode        object
CategoryID          int64
dtype: object

Missing values:
CommentID          0
VideoID            0
VideoTitle         0
AuthorName         0
AuthorChannelID    0
CommentText        0
Sentiment          0
Likes              0
Replies            0
PublishedAt        0
CountryCode        0
CategoryID         0
dtype: int64

Duplicate rows: 0

Unique values per column:
CommentID          989252
VideoID              4563
VideoTitle           4564
AuthorName         732069
AuthorChannelID    731967
CommentText        989258
Sentiment               3
Likes                7570
Replies               527
PublishedAt        756536
CountryCode             9
CategoryID             11
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
df['Sentiment'].value_counts()

Sentiment
Negative    339255
Neutral     326104
Positive    323899
Name: count, dtype: int64

In [41]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

Shape: (1031594, 12)
Columns: ['CommentID', 'VideoID', 'VideoTitle', 'AuthorName', 'AuthorChannelID', 'CommentText', 'Sentiment', 'Likes', 'Replies', 'PublishedAt', 'CountryCode', 'CategoryID']

In [42]:
df.info()
display(df.head(10))
display(df.sample(10, random_state=42))

<class 'pandas.core.frame.DataFrame'>
Index: 1031594 entries, 0 to 1032224
Data columns (total 12 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   CommentID        1031594 non-null  object
 1   VideoID          1031594 non-null  object
 2   VideoTitle       1031594 non-null  object
 3   AuthorName       1031594 non-null  object
 4   AuthorChannelID  1031594 non-null  object
 5   CommentText      1031594 non-null  object
 6   Sentiment        1031594 non-null  object
 7   Likes            1031594 non-null  int64
 8   Replies          1031594 non-null  int64
 9   PublishedAt      1031594 non-null  object
 10  CountryCode      1031594 non-null  object
 11  CategoryID       1031594 non-null  int64
dtypes: int64(3), object(9)
memory usage: 102.3+ MB

,CommentID,VideoID,VideoTitle,AuthorName,AuthorChannelID,CommentText,Sentiment,Likes,Replies,PublishedAt,CountryCode,CategoryID
0,UgyRjrEdJIPrf68uND14AaABAg,mcY4M9gjtsI,They killed my friend.#tales #movie #shorts,@OneWhoWandered,UC_-UEXaBL1dqqUPGkDll49A,Anyone know what movie this is?,Neutral,0,2,2025-01-15 00:54:55,NZ,1
1,UgxXxEIySAwnMNw8D7N4AaABAg,2vuXcw9SZbA,Man Utd conceding first penalty at home in yea...,@chiefvon3068,UCZ1LcZESjYqzaQRhjdZJFwg,The fact they're holding each other back while...,Positive,0,0,2025-01-13 23:51:46,AU,17
2,UgxB0jh2Ur41mcXr5IB4AaABAg,papg2tsoFzg,Welcome to Javascript Course,@Abdulla-ip8qr,UCWBK35w5Swy1iF5xIbEyw3A,waiting next video will be?,Neutral,1,0,2020-07-06 13:18:16,IN,27
3,UgwMOh95MfK0GuXLLrF4AaABAg,31KTdfRH6nY,Building web applications in Java with Spring ...,@finnianthehuman,UCwQ2Z03nOcMxWozBb_Cv66w,Thanks for the great video.\n\nI don't underst...,Neutral,0,1,2024-09-18 12:04:12,US,27
4,UgxJuUe5ysG8OSbABAl4AaABAg,-hV6aeyPHPA,After a new engine her car dies on her way hom...,@ryoutubeplaylistb6137,UCTTcJ0tsAKQokmHB2qVb1qQ,Good person helping good people.\nThis is how ...,Positive,3,1,2025-01-10 19:39:03,US,2
5,UgzoTpY5F11FtcooFRR4AaABAg,NnJ4XJdZW4I,The lawyer brilliantly got it out of the way #...,@TrymAndresBernes,UCX_OJCxRZDFELHrLemK4ONw,Dei løk de seim😂,Neutral,0,0,2025-01-14 20:23:42,NZ,1
6,UgzJ-2rV0-YNPyMj0u14AaABAg,X4wNLFrv9Co,Which one will you choose to use the cola keyc...,@JasmineHatchel-c3c,UCHvnyO2K7-1oXXdWQh0510g,Number two because it looks the best with it,Positive,0,0,2025-01-10 06:00:19,US,28
7,UgwuFh4s9cHu3dHrPqJ4AaABAg,sKniMxl9zwo,Trump’s Reaction During ‘Abuse of Power’ Says ...,@StaceyBrown-h6o,UCzTaRiUaLcaLD9I0l2tCBCA,Thank God we don’t have to listen to his drive...,Positive,0,0,2025-01-14 01:24:48,IE,25
8,UgwzYX76p4RK8AHVcYN4AaABAg,yUImrnDqGUk,Thank god this angel found this beautiful dog ...,@cassiegerst6123,UC-QvE5-ZberkWmSYDXLvfQA,Very similar thing happened to me! We lived ne...,Positive,0,0,2025-01-14 03:54:19,AU,15
9,UgzW7h-gmtmgIFFClLJ4AaABAg,5VPxcrvVkBc,He betrayed his own friend - Enjoying a cup of...,@josh_playz2709,UCflV1g1fmgs5i2QZwiaHT8g,im about to cry😢,Negative,0,0,2025-01-13 09:55:03,IE,20

,CommentID,VideoID,VideoTitle,AuthorName,AuthorChannelID,CommentText,Sentiment,Likes,Replies,PublishedAt,CountryCode,CategoryID
347213,Ugzk3eMUp1ARPzL3scN4AaABAg,BF5SzIN63w8,Inside the brain of a gambling addict - BBC News,@Mary-b8x8u,UChUyhuh6LNs-udDF4Rpj-FA,i like this video ahahehah Inside the brain of...,Neutral,0,0,2025-01-17 12:54:07,GB,25
687089,UgzoLyeW0mOs01oWJ8F4AaABAg,hRbIshSsrt4,this speedrun is insane,@Yapdollar-the-real-one,UC-oLCkHXQ1g8OVe6UB6nS0Q,My birthday is at August 9th bro😭🙏,Neutral,2,1,2025-01-14 16:37:58,IE,20
630461,UgxDCBnNVkyGLlozitJ4AaABAg,9QCeQ9Mtuc4,Her doorbell camera caught a deer red handed 😂,@asuniqueasthespellingofmyn1124,UCydAXKvSCfluTc6OeJ9NFKQ,That was amazingly entertaining 😅🎉,Positive,8,0,2025-01-04 20:27:39,US,15
493388,Ugx0C7dMnx8mgIjIzup4AaABAg,irqbmMNs2Bo,C Language Tutorial for Beginners (with Notes ...,@muskaankour9910,UCpTqG7ZKXDow0e2VfVrtzdQ,"In my entire 1 st year ,I did'nt understand th...",Positive,1662,42,2022-08-06 15:37:05,IN,27
623703,UgzjvNhPxsE1MGMTwvp4AaABAg,z5XSFam4YYE,*BRAND NEW* DOLLAR TREE ORGANIZATION product l...,@pinkg5852,UCEEjh4uo1bCFv3FyDGUZgHg,Thanks for the tips.\nJesus Loves You So Much 😊,Positive,0,0,2025-01-12 00:01:41,CA,22
162956,UgzOymdx0Jt6_i50TM94AaABAg_aug,LTaiNs3vu38,"this is detrimental, can't believe this happen...",AugmentedUser,AugmentedCID,"Since California is so important to you, why n...",Negative,0,0,2025-02-04 02:24:12,CA,22
363531,UgwBLoMVNKO43q2MLIB4AaABAg,ysYGCtGYGdc,Anthony Bourdain: Iran not what I expected (Pa...,@Msmira3,UCeNB2qaYKdnv6V8X35rJw1w,Thank you Anthony Bourdain for all what you ga...,Positive,2,0,2018-06-11 04:30:43,US,25
660786,UgyBLHj-wIUwdo35ILJ4AaABAg,Do-buN3KSkU,Who has sent weapons to Ukraine?,@trentriver,UCLLD58gZ6CDu5lXyc93s6JA,Canada has sent considerable lethal and non-le...,Positive,174,28,2022-03-04 23:07:41,GB,25
120726,Ugx0h3VWowBPlvDxxxl4AaABAg,ENJuNCkPfx0,My Life As A One-Man Band | Tommy Emmanuel | T...,@thefiddler83,UCcVxy9vJ_q6xgchste_KfWw,I love this camera director..pointed exactly w...,Positive,0,0,2024-09-18 09:19:28,US,25
561166,Ugw6KP0tOV2q0PwjvUl4AaABAg,scUrBuvhOQA,Election Day 2020 Is HERE | Ep. 1129,@zavistyle6080,UCka-4TZVfhMHjHShDFspLsA,Two words: 2x speed,Neutral,0,0,2020-11-04 17:20:50,US,25

In [43]:
print("Missing values:")
display(df.isnull().sum().sort_values(ascending=False))

print("Fully duplicated rows:", df.duplicated().sum())

Missing values:

CommentID          0
VideoID            0
VideoTitle         0
AuthorName         0
AuthorChannelID    0
CommentText        0
Sentiment          0
Likes              0
Replies            0
PublishedAt        0
CountryCode        0
CategoryID         0
dtype: int64

Fully duplicated rows: 0

In [44]:

print("Unique sentiment classes:")
print(df["Sentiment"].unique())

Unique sentiment classes:
['Neutral' 'Positive' 'Negative']

In [45]:
df['CommentText'].describe()

count     1031594
unique     989271
top             ❤
freq         1169
Name: CommentText, dtype: object

In [46]:
# Phase 3: Data cleaning

clean_df=df.copy()
clean_df['CommentText']=clean_df['CommentText'].str.strip()

In [47]:
clean_df = clean_df.dropna(
    subset=["CommentText", "Sentiment"]
).copy()

In [48]:
clean_df = clean_df[
    clean_df["CommentText"].ne("")
].copy()

In [49]:

print("Rows before cleaning:", len(df))
print("Rows after cleaning:", len(clean_df))
print("Rows removed:", len(df) - len(clean_df))

Rows before cleaning: 1031594
Rows after cleaning: 1031433
Rows removed: 161

In [50]:
#  Remove duplicate records

clean_df['CommentText'].duplicated().sum()

np.int64(42175)

In [51]:
clean_df.head()

,CommentID,VideoID,VideoTitle,AuthorName,AuthorChannelID,CommentText,Sentiment,Likes,Replies,PublishedAt,CountryCode,CategoryID
0,UgyRjrEdJIPrf68uND14AaABAg,mcY4M9gjtsI,They killed my friend.#tales #movie #shorts,@OneWhoWandered,UC_-UEXaBL1dqqUPGkDll49A,Anyone know what movie this is?,Neutral,0,2,2025-01-15 00:54:55,NZ,1
1,UgxXxEIySAwnMNw8D7N4AaABAg,2vuXcw9SZbA,Man Utd conceding first penalty at home in yea...,@chiefvon3068,UCZ1LcZESjYqzaQRhjdZJFwg,The fact they're holding each other back while...,Positive,0,0,2025-01-13 23:51:46,AU,17
2,UgxB0jh2Ur41mcXr5IB4AaABAg,papg2tsoFzg,Welcome to Javascript Course,@Abdulla-ip8qr,UCWBK35w5Swy1iF5xIbEyw3A,waiting next video will be?,Neutral,1,0,2020-07-06 13:18:16,IN,27
3,UgwMOh95MfK0GuXLLrF4AaABAg,31KTdfRH6nY,Building web applications in Java with Spring ...,@finnianthehuman,UCwQ2Z03nOcMxWozBb_Cv66w,Thanks for the great video.\n\nI don't underst...,Neutral,0,1,2024-09-18 12:04:12,US,27
4,UgxJuUe5ysG8OSbABAl4AaABAg,-hV6aeyPHPA,After a new engine her car dies on her way hom...,@ryoutubeplaylistb6137,UCTTcJ0tsAKQokmHB2qVb1qQ,Good person helping good people.\nThis is how ...,Positive,3,1,2025-01-10 19:39:03,US,2

In [52]:
clean_df = clean_df.drop_duplicates(
    subset=["CommentText"],
    keep="first"
).copy()

clean_df = clean_df.reset_index(drop=True)

print("Shape after duplicate removal:", clean_df.shape)

Shape after duplicate removal: (989258, 12)

In [53]:
# Check the remaining data quality
print("Missing comments:", clean_df["CommentText"].isna().sum())
print("Empty comments:", clean_df["CommentText"].str.strip().eq("").sum())
print("Missing labels:", clean_df["Sentiment"].isna().sum())

display(clean_df["Sentiment"].value_counts())

Missing comments: 0
Empty comments: 0
Missing labels: 0

Sentiment
Negative    339255
Neutral     326104
Positive    323899
Name: count, dtype: int64

In [54]:
# saving it 
clean_df.to_csv(
    "youtube_comments_cleaned.csv",
    index=False
)

In [55]:
import html ,re

# Text preprocessing
def preprocess_text(text):
    text = str(text)

    # Decode HTML entities
    text = html.unescape(text)

    # Remove HTML tags where present
    text = re.sub(r"<[^>]+>", " ", text)

    # Replace URLs with a token
    text = re.sub(
        r"https?://\S+|www\.\S+",
        " URL ",
        text
    )

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [56]:
clean_df['CommentText'].apply(preprocess_text)

0                           Anyone know what movie this is?
1         The fact they're holding each other back while...
2                               waiting next video will be?
3         Thanks for the great video. I don't understand...
4         Good person helping good people. This is how i...
                                ...
989253    me here just to read peoples comments about th...
989254    Any recommendations for how to build on top of...
989255              Act foolishly, receive foolish rewards.
989256    I think many people would like to know the mod...
989257                                         Why no rust?
Name: CommentText, Length: 989258, dtype: object

In [57]:
test_comments = [
    "I LOVE this video!!! 😍😍",
    "This is not good at all.",
    "Visit https://example.com for more info",
    "This is great &amp; amazing!"
]

for comment in test_comments:
    print("Original:", comment)
    print("Processed:", preprocess_text(comment))
    print()

Original: I LOVE this video!!! 😍😍
Processed: I LOVE this video!!! 😍😍

Original: This is not good at all.
Processed: This is not good at all.

Original: Visit https://example.com for more info
Processed: Visit URL for more info

Original: This is great &amp; amazing!
Processed: This is great & amazing!

In [58]:
# import matplotlib.pyplot as plt
# import seaborn as sns

# sentiments_count=clean_df['Sentiment'].value_counts()

# display(sentiments_count)


# plt.figure(figsize=(8,5))

# sns.countplot(
#     data=clean_df,
#     x='Sentiment',
#     order=classes
# )
# plt.title("Sentiment Distribution")
# plt.xlabel("Sentiment")
# plt.ylabel("Number of comments")
# plt.tight_layout()
# plt.show()

In [59]:
sentiment_percentages = (
    clean_df["Sentiment"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

display(sentiment_percentages)

Sentiment
Negative    34.29
Neutral     32.96
Positive    32.74
Name: proportion, dtype: float64

In [60]:
import re
import html
import nltk
import emoji

from nltk.corpus import stopwords, wordnet
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag

nltk.download("stopwords")
nltk.download("punkt_tab")
nltk.download("wordnet")
nltk.download("averaged_perceptron_tagger_eng")
nltk.download("omw-1.4")

print("NLP libraries ready")

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /usr/share/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...

NLP libraries ready

In [61]:
# Keep only rows with valid text and labels
experiment_df = clean_df.dropna(
    subset=["CommentText", "Sentiment"]
).copy()

experiment_df["CommentText"] = (
    experiment_df["CommentText"].astype(str).str.strip()
)

experiment_df = experiment_df[
    experiment_df["CommentText"].ne("")
].copy()

print("Dataset shape:", experiment_df.shape)
display(experiment_df[["CommentText", "Sentiment"]].head())

Dataset shape: (989258, 12)

                                         CommentText Sentiment
0                    Anyone know what movie this is?   Neutral
1  The fact they're holding each other back while...  Positive
2                        waiting next video will be?   Neutral
3  Thanks for the great video.\n\nI don't underst...   Neutral
4  Good person helping good people.\nThis is how ...  Positive

In [62]:
def basic_clean(text):
    text = html.unescape(str(text))
    text = re.sub(r"<[^>]+>", " ", text)

    # Replace URLs, rather than deleting them silently
    text = re.sub(
        r"https?://\S+|www\.\S+",
        " URL ",
        text
    )

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [63]:
experiment_df["CommentText"].apply(basic_clean)

0                           Anyone know what movie this is?
1         The fact they're holding each other back while...
2                               waiting next video will be?
3         Thanks for the great video. I don't understand...
4         Good person helping good people. This is how i...
                                ...
989253    me here just to read peoples comments about th...
989254    Any recommendations for how to build on top of...
989255              Act foolishly, receive foolish rewards.
989256    I think many people would like to know the mod...
989257                                         Why no rust?
Name: CommentText, Length: 989258, dtype: object

In [64]:
display(experiment_df[["CommentText", "Sentiment"]].head())

                                         CommentText Sentiment
0                    Anyone know what movie this is?   Neutral
1  The fact they're holding each other back while...  Positive
2                        waiting next video will be?   Neutral
3  Thanks for the great video.\n\nI don't underst...   Neutral
4  Good person helping good people.\nThis is how ...  Positive

In [65]:
experiment_df['CommentText'].str.replace('\n','')

0                           Anyone know what movie this is?
1         The fact they're holding each other back while...
2                               waiting next video will be?
3         Thanks for the great video.I don't understand ...
4         Good person helping good people.This is how it...
                                ...
989253    me here just to read peoples comments about th...
989254    Any recommendations for how to build on top of...
989255              Act foolishly, receive foolish rewards.
989256    I think many people would like to know the mod...
989257                                         Why no rust?
Name: CommentText, Length: 989258, dtype: object

In [66]:
# lemmatizer = WordNetLemmatizer()

# def get_wordnet_pos(tag):
#     if tag.startswith("J"):
#         return wordnet.ADJ
#     elif tag.startswith("V"):
#         return wordnet.VERB
#     elif tag.startswith("N"):
#         return wordnet.NOUN
#     elif tag.startswith("R"):
#         return wordnet.ADV
#     else:
#         return wordnet.NOUN


# def apply_lemmatization(text):
#     tokens = word_tokenize(basic_clean(text))
#     tagged_tokens = pos_tag(tokens)

#     lemmatized_tokens = []

#     for word, tag in tagged_tokens:
#         pos = get_wordnet_pos(tag)

#         lemma = lemmatizer.lemmatize(
#             word,
#             pos=pos
#         )

#         lemmatized_tokens.append(lemma)

#     return " ".join(lemmatized_tokens)


# experiment_df['lemmatization']=experiment_df['CommentText'].apply(apply_lemmatization)

In [67]:
stop_words = set(stopwords.words("english"))

# Keep words that can reverse or change sentiment
important_words = {
    "no", "nor", "not", "never",
    "don't", "doesn't", "didn't",
    "isn't", "aren't", "wasn't", "weren't",
    "can't", "couldn't", "won't", "wouldn't",
    "shouldn't", "haven't", "hasn't", "hadn't"
}

stop_words = stop_words - important_words

def remove_stopwords(text):
    tokens = word_tokenize(basic_clean(text))

    filtered_tokens = [
        word for word in tokens
        if word.lower() not in stop_words
    ]

    return " ".join(filtered_tokens)

experiment_df['CommentText'].apply(remove_stopwords)

0                                       Anyone know movie ?
1               fact 're holding back equally aggressive 😂😂
2                                      waiting next video ?
3         Thanks great video . n't understand DB continu...
4         Good person helping good people . America exce...
                                ...
989253               read peoples comments hate ban laugh .
989254    recommendations build top ? Add complexity , i...
989255            Act foolishly , receive foolish rewards .
989256    think many people would like know model Black ...
989257                                            no rust ?
Name: CommentText, Length: 989258, dtype: object

In [68]:
def remove_punctuation(text):
    text = basic_clean(text)

    # Keep letters, numbers, and whitespace
    # Remove punctuation and symbols
    text = re.sub(r"[^\w\s]", " ", text)

    return re.sub(r"\s+", " ", text).strip()

experiment_df['CommentText'].apply(remove_punctuation)

0                            Anyone know what movie this is
1         The fact they re holding each other back while...
2                                waiting next video will be
3         Thanks for the great video I don t understand ...
4         Good person helping good people This is how it...
                                ...
989253    me here just to read peoples comments about th...
989254    Any recommendations for how to build on top of...
989255                Act foolishly receive foolish rewards
989256    I think many people would like to know the mod...
989257                                          Why no rust
Name: CommentText, Length: 989258, dtype: object

In [69]:
def remove_emojis(text):
    text=basic_clean(text)
    return emoji.replace_emoji(
        text,
        replace=''
    )
experiment_df['CommentText'].apply(remove_emojis)

0                           Anyone know what movie this is?
1         The fact they're holding each other back while...
2                               waiting next video will be?
3         Thanks for the great video. I don't understand...
4         Good person helping good people. This is how i...
                                ...
989253    me here just to read peoples comments about th...
989254    Any recommendations for how to build on top of...
989255              Act foolishly, receive foolish rewards.
989256    I think many people would like to know the mod...
989257                                         Why no rust?
Name: CommentText, Length: 989258, dtype: object

In [70]:
# check the experiment_df

experiment_df['CommentText'].iloc[90]

"The LeetCode instructions were absolutely awful for this question. They rarely seem to explain stuff in simple terms, it's so annoying. Half the battle is deciphering the question itself, sometimes the code isn't even hard to come up with, just interpreting the question."

In [73]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


# Download necessary resources
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')



def remove_stopwords(text):
  # Get English stop words set
  stop_words = set(stopwords.words("english"))

  # Tokenize the input text into words
  word_tokens = word_tokenize(text)

  # Filter out words present in the stop words set (case-insensitive)
  filtered_words = [w for w in word_tokens if w.lower() not in stop_words]

  return " ".join(filtered_words)


experiment_df['CommentText'].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

0                                       Anyone know movie ?
1               fact 're holding back equally aggressive 😂😂
2                                      waiting next video ?
3         Thanks great video . n't understand DB continu...
4         Good person helping good people . America exce...
                                ...
989253               read peoples comments hate ban laugh .
989254    recommendations build top ? Add complexity , i...
989255            Act foolishly , receive foolish rewards .
989256    think many people would like know model Black ...
989257                                               rust ?
Name: CommentText, Length: 989258, dtype: object

In [75]:
experiment_df['CommentText'].iloc[90]

"The LeetCode instructions were absolutely awful for this question. They rarely seem to explain stuff in simple terms, it's so annoying. Half the battle is deciphering the question itself, sometimes the code isn't even hard to come up with, just interpreting the question."

In [74]:
clean_df.to_csv(
    "youtube_comments_cleaned3.csv",
    index=False
)

In [ ]:
from sklearn.model_selection import train_test_split
model_df=experiment_df[
    ["CommentText", "Sentiment"]
].dropna().copy()

In [78]:
model_df['CommentText']=model_df['CommentText'].str.strip()
model_df = model_df[
    model_df["CommentText"].ne("")
].copy()

# Check sentiment distribution
print("Dataset shape:", model_df.shape)
print(model_df["Sentiment"].value_counts())
print(model_df["Sentiment"].value_counts(normalize=True).round(3))

Dataset shape: (989258, 2)
Sentiment
Negative    339255
Neutral     326104
Positive    323899
Name: count, dtype: int64
Sentiment
Negative    0.343
Neutral     0.330
Positive    0.327
Name: proportion, dtype: float64

In [79]:
# split the dataset 

X=model_df['CommentText']
y = model_df["Sentiment"]

X_train,X_test,y_train,y_test=train_test_split(
    X,y,
    test_size=0.2,
    random_state=42
)
print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

Training rows: 791406
Testing rows: 197852

In [82]:
# compare models 

import time

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import LinearSVC


from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

models={
    "MultinomialNB":MultinomialNB(),
    'LogesticRegression':LogisticRegression(
        max_iter=1000,
        C=1.0
    ),
    'LinearSVC':LinearSVC(
        C=1.0,
        random_state=42
    ),
    "SGDClassifier": SGDClassifier(
        loss="hinge",
        max_iter=1000,
        tol=1e-3,
        random_state=42
    )
    
    
}

In [84]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

model=Pipeline([
    ('tfidf',TfidfVectorizer(
        max_features=100_000,
        ngram_range=(1,2),
        min_df=2,
        sublinear_tf=True,
        dtype="float32"
    )),
    ('classifier',LogisticRegression(max_iter=100))
])
model.fit(X_train, y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/feature_extraction/text.py:2043: UserWarning: Only (<class 'numpy.float64'>, <class 'numpy.float32'>, <class 'numpy.float16'>) 'dtype' should be used. float32 'dtype' will be converted to np.float64.
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(dtype='float32', max_features=100000, min_df=2,
                                 ngram_range=(1, 2), sublinear_tf=True)),
                ('classifier', LogisticRegression())])

In [86]:
y_pred=model.predict(X_test)
print("accuracy:",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

accuracy: 0.7019388229585751
              precision    recall  f1-score   support

    Negative       0.70      0.72      0.71     67851
     Neutral       0.64      0.67      0.66     65186
    Positive       0.77      0.72      0.74     64815

    accuracy                           0.70    197852
   macro avg       0.70      0.70      0.70    197852
weighted avg       0.70      0.70      0.70    197852

In [88]:

import time
import numpy as np
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.linear_model import LogisticRegression, SGDClassifier, RidgeClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB, ComplementNB
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from xgboost import XGBClassifier

# 1. Define the candidate models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Linear SVM": LinearSVC(),
    "Multinomial Naive Bayes": MultinomialNB(),
    "Complement Naive Bayes": ComplementNB(),
    "SGD Classifier": SGDClassifier(random_state=42),
    "Ridge Classifier": RidgeClassifier()
}

# 2. Use identical CV folds for all models
cv = StratifiedKFold(
    n_splits=3,
    shuffle=True,
    random_state=42
)

results = []

# 3. Train and evaluate each model
for name, classifier in models.items():
    print(f"\nTraining: {name}")
    start = time.time()

    pipeline = Pipeline([
        ("tfidf", TfidfVectorizer(
            max_features=100_000,
            ngram_range=(1, 2),
            min_df=2,
            sublinear_tf=True,
            dtype=np.float32
        )),
        ("classifier", classifier)
    ])

    scores = cross_validate(
        pipeline,
        X_train,
        y_train,
        cv=cv,
        scoring={
            "accuracy": "accuracy",
            "macro_f1": "f1_macro"
        },
        n_jobs=1,
        return_train_score=False,
        error_score="raise"
    )

    elapsed = time.time() - start

    results.append({
        "Model": name,
        "CV Accuracy": scores["test_accuracy"].mean(),
        "CV Macro F1": scores["test_macro_f1"].mean(),
        "F1 Std": scores["test_macro_f1"].std(),
        "Time (min)": elapsed / 60
    })

    print(f"Macro F1: {scores['test_macro_f1'].mean():.4f}")
    print(f"Time: {elapsed / 60:.2f} minutes")

# 4. Display the leaderboard
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(
    "CV Macro F1", ascending=False
).reset_index(drop=True)

display(
    results_df.style.format({
        "CV Accuracy": "{:.4f}",
        "CV Macro F1": "{:.4f}",
        "F1 Std": "{:.4f}",
        "Time (min)": "{:.2f}"
    })
)

print("\nBest model:", results_df.iloc[0]["Model"])
print("Best CV Macro F1:", round(results_df.iloc[0]["CV Macro F1"], 4))

Training: Logistic Regression
Macro F1: 0.7024
Time: 7.12 minutes

Training: Linear SVM
Macro F1: 0.6908
Time: 7.15 minutes

Training: Multinomial Naive Bayes

KeyboardInterrupt:

In [ ]:
import pandas as pd

results_df = pd.DataFrame(results)

display(
    results_df.sort_values("CV Macro F1", ascending=False)
    .style.format({
        "CV Accuracy": "{:.4f}",
        "CV Macro F1": "{:.4f}",
        "F1 Std": "{:.4f}",
        "Time (min)": "{:.2f}"
    })
)

In [ ]:

import time
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, StratifiedKFold

pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=100_000,
        ngram_range=(1, 2),
        min_df=2,
        sublinear_tf=True,
        dtype=np.float32
    )),
    ("classifier", LogisticRegression(max_iter=1000))
])

param_grid = {
    "tfidf__max_features": [50_000, 100_000],
    "tfidf__ngram_range": [(1, 1), (1, 2)],
    "classifier__C": [0.5, 1.0, 2.0]
}

cv = StratifiedKFold(
    n_splits=3,
    shuffle=True,
    random_state=42
)

grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    scoring="f1_macro",
    cv=cv,
    n_jobs=1,
    verbose=2,
    refit=True
)

start = time.time()
grid_search.fit(X_train, y_train)

print("\nBest parameters:", grid_search.best_params_)
print("Best CV Macro F1:", round(grid_search.best_score_, 4))
print("Time taken (minutes):", round((time.time() - start) / 60, 2))

Fitting 3 folds for each of 12 candidates, totalling 36 fits
[CV] END classifier__C=0.5, tfidf__max_features=50000, tfidf__ngram_range=(1, 1); total time= 1.3min
[CV] END classifier__C=0.5, tfidf__max_features=50000, tfidf__ngram_range=(1, 1); total time= 1.1min
[CV] END classifier__C=0.5, tfidf__max_features=50000, tfidf__ngram_range=(1, 1); total time= 1.2min
[CV] END classifier__C=0.5, tfidf__max_features=50000, tfidf__ngram_range=(1, 2); total time= 2.0min
[CV] END classifier__C=0.5, tfidf__max_features=50000, tfidf__ngram_range=(1, 2); total time= 2.0min
[CV] END classifier__C=0.5, tfidf__max_features=50000, tfidf__ngram_range=(1, 2); total time= 2.0min
[CV] END classifier__C=0.5, tfidf__max_features=100000, tfidf__ngram_range=(1, 1); total time= 1.2min
[CV] END classifier__C=0.5, tfidf__max_features=100000, tfidf__ngram_range=(1, 1); total time= 1.3min
[CV] END classifier__C=0.5, tfidf__max_features=100000, tfidf__ngram_range=(1, 1); total time= 1.1min
[CV] END classifier__C=0.5, tfidf__max_features=100000, tfidf__ngram_range=(1, 2); total time= 2.0min
[CV] END classifier__C=0.5, tfidf__max_features=100000, tfidf__ngram_range=(1, 2); total time= 2.4min
[CV] END classifier__C=0.5, tfidf__max_features=100000, tfidf__ngram_range=(1, 2); total time= 2.0min
[CV] END classifier__C=1.0, tfidf__max_features=50000, tfidf__ngram_range=(1, 1); total time= 1.5min

In [ ]:

import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import time

final_model = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=100_000,
        ngram_range=(1, 2),
        min_df=2,
        sublinear_tf=True,
        dtype=np.float32
    )),
    ("classifier", LogisticRegression(
        C=1.0,
        max_iter=1000
    ))
])

start = time.time()

final_model.fit(X_train, y_train)
final_pred = final_model.predict(X_test)

print("Final Test Accuracy:",
      round(accuracy_score(y_test, final_pred), 4))

print("\nClassification Report:\n")
print(classification_report(y_test, final_pred))

print("Training and evaluation time:",
      round((time.time() - start) / 60, 2), "minutes")

In [ ]:
%pip install -U transformers torch accelerate scikit-learn pandas tqdm

In [ ]:
import torch
from transformers import pipeline

MODEL_NAME = "cardiffnlp/twitter-roberta-base-sentiment-latest"

device = 0 if torch.cuda.is_available() else -1

sentiment_model = pipeline(
    task="text-classification",
    model=MODEL_NAME,
    tokenizer=MODEL_NAME,
    device=device
)

print("Model loaded successfully!")
print("Device:", "GPU" if device == 0 else "CPU")

In [ ]:
comments = [
    "This video is amazing, I really enjoyed it!",
    "The video is okay, nothing special.",
    "This is terrible and completely boring.",
    "I don't like this video at all."
]

predictions = sentiment_model(
    comments,
    batch_size=4,
    truncation=True
)

for comment, result in zip(comments, predictions):
    print("Comment:", comment)
    print("Sentiment:", result["label"])
    print("Confidence:", round(result["score"], 4))
    print("-" * 60)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Select a representative test sample
eval_size = min(5000, len(X_test))

X_hf_eval, _, y_hf_eval, _ = train_test_split(
    X_test,
    y_test,
    train_size=eval_size,
    random_state=42,
    stratify=y_test
)

# Run predictions in batches
hf_results = sentiment_model(
    X_hf_eval.tolist(),
    batch_size=16,
    truncation=True
)

hf_predictions = [r["label"].title() for r in hf_results]

# Normalize actual labels
y_actual = y_hf_eval.astype(str).str.strip().str.title()

print(classification_report(
    y_actual,
    hf_predictions,
    labels=["Negative", "Neutral", "Positive"],
    zero_division=0
))

print("Accuracy:", accuracy_score(y_actual, hf_predictions))
print("Macro F1:", f1_score(
    y_actual, hf_predictions, average="macro", zero_division=0
))

In [ ]:
import os
import joblib

# Create a folder for the trained model
os.makedirs("models", exist_ok=True)

joblib.dump(final_model,'models/sentiment_pipeline.pkl')
print("Model saved successfully!")
print("File: models/sentiment_pipeline.pkl"))

In [ ]:
import joblib
loaded_model = joblib.load("models/sentiment_pipeline.pkl")

simple_comments=[
     "This video is amazing, I really enjoyed it!",
    "This video is okay, nothing special.",
    "This is terrible, I completely hate it."
]
predictions=loaded_model.predict(sample_comments)

for comment, sentiment in zip(sample_comments, predictions):
    print(f"Comment: {comment}")
    print(f"Predicted sentiment: {sentiment}\n")

In [ ]:
# saving huggin face model 
import os
import joblib
from transformers import pipeline

# Load the Hugging Face model
hugging_model = pipeline(
    "text-classification",
    model="cardiffnlp/twitter-roberta-base-sentiment-latest"
)

# Create folder
os.makedirs("models", exist_ok=True)

# Save the complete pipeline
joblib.dump(
    hugging_model,
    "models/huggingface_sentiment_pipeline.pkl"
)

print("Model saved successfully!")
print("File: models/huggingface_sentiment_pipeline.pkl")

In [ ]:
import joblib

loaded_model = joblib.load(
    "models/huggingface_sentiment_pipeline.pkl"
)

simple_comments = [
    "This video is amazing, I really enjoyed it!",
    "This video is okay, nothing special.",
    "This is terrible, I completely hate it."
]

predictions = loaded_model(
    simple_comments,
    batch_size=3,
    truncation=True
)

for comment, result in zip(simple_comments, predictions):
    print(f"Comment: {comment}")
    print(f"Predicted sentiment: {result['label'].title()}")
    print(f"Confidence: {result['score']:.4f}\n")